version: '3.8'

networks:
  vietnamese-healthcare-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  # Milvus Vector Database for Vietnamese Medical Knowledge
  milvus:
    image: milvusdb/milvus:v2.3.0
    container_name: carecircle-milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - milvus-data:/var/lib/milvus
      - ./milvus.yaml:/milvus/configs/milvus.yaml
    networks:
      - vietnamese-healthcare-network
    restart: unless-stopped
    depends_on:
      - etcd
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # etcd for Milvus metadata storage
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: carecircle-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd-data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - vietnamese-healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO for Milvus object storage
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: carecircle-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: minio server /data --console-address ":9001"
    networks:
      - vietnamese-healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Vietnamese Healthcare Session Management
  redis-vietnamese:
    image: redis:7-alpine
    container_name: carecircle-redis-vietnamese
    ports:
      - "6380:6379"
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis-vietnamese-data:/data
      - ./redis-vietnamese.conf:/usr/local/etc/redis/redis.conf
    networks:
      - vietnamese-healthcare-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Vietnamese NLP Processing Service (Python)
  vietnamese-nlp:
    build:
      context: ./vietnamese-nlp
      dockerfile: Dockerfile
    container_name: carecircle-vietnamese-nlp
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
      - REDIS_URL=redis://redis-vietnamese:6379/0
    volumes:
      - ./vietnamese-nlp/models:/app/models
      - ./vietnamese-nlp/data:/app/data
    networks:
      - vietnamese-healthcare-network
    restart: unless-stopped
    depends_on:
      - redis-vietnamese
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  milvus-data:
    driver: local
  etcd-data:
    driver: local
  minio-data:
    driver: local
  redis-vietnamese-data:
    driver: local

# Vietnamese Healthcare Development Commands:
# Start all services: docker-compose -f docker-compose.vietnamese-healthcare.yml up -d
# Start only vector database: docker-compose -f docker-compose.vietnamese-healthcare.yml up -d milvus etcd minio
# View logs: docker-compose -f docker-compose.vietnamese-healthcare.yml logs -f milvus
# Stop all services: docker-compose -f docker-compose.vietnamese-healthcare.yml down
# Reset data: docker-compose -f docker-compose.vietnamese-healthcare.yml down -v
