name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^16.0.0

  # Internationalization
  intl: ^0.20.2

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3

  # Local Storage
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Authentication
  local_auth: ^2.1.6
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_crashlytics: ^4.1.3
  google_sign_in: ^7.1.0
  sign_in_with_apple: ^7.0.1

  # Health Integration
  health: ^13.1.1

  # Notifications
  flutter_local_notifications: ^19.3.0

  # External Services
  url_launcher: ^6.2.2

  # UI Components (Design System)
  flutter_hooks: ^0.21.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

  # AI Assistant Interface
  speech_to_text: ^7.1.0
  flutter_tts: ^4.2.3
  flutter_chat_core: ^2.6.2
  flutter_chat_ui: ^2.6.2
  flutter_chat_types: ^3.6.2

  # Healthcare UI Components
  percent_indicator: ^4.2.3

  # Design System
  flex_color_scheme: ^8.2.0

  # Logging System
  talker_flutter: ^4.8.3
  logger: ^2.4.0
  path_provider: ^2.1.4

  # Utilities
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.1
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0

  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2
  timezone: ^0.10.1
  firebase_messaging: ^15.2.9

  # Charts and Data Visualization
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^9.2.0

  # JSON Serialization Code Generation
  json_serializable: ^6.9.5
  freezed: ^3.1.0

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
